using UnityEngine;
using System.Collections.Generic;
using System.Linq;
using EventBus;
using TMPro;

public class PayoutSchemes : MonoBehaviour
{
    /*
     * Draft generated by github copilot
     * model: Claude Sonnet 4.5
     * prompt:
     * The payout scheme is an observer over the 5x5 grid of SlotState.cs scripts. All 25 slot states are children GameObjects underneath this script gameObject.
        You must implement a minimum of five different payout schemes, such as: Matching symbols in a row or column Diagonal matches Clusters of identical symbols Special symbol combinations (e.g., wildcards or bonus icons) Full grid patterns (e.g., all corners match) Each scheme should have its own reward logic
        We need the follwing logic:
        You must implement a minimum of five different payout schemes, such as:

        Matching symbols in a row or column
        Diagonal matches
        Clusters of identical symbols
        Special symbol combinations (e.g., wildcards or bonus icons)
        Full grid patterns (e.g., all corners match)
     */
    [Header("Grid Settings")]
    [SerializeField]
    int gridSize = 5;
    
    [Header("Wildcard Settings")]
    [SerializeField]
    int wildcardValue = -1; // Set to -1 to disable wildcards
    [Tooltip("If true, wildcard value will match any symbol")]
    [SerializeField]
    bool enableWildcards;
    
    [Header("Payout Multipliers")]
    [SerializeField] float rowMatchMultiplier = 5f;
    [SerializeField] float columnMatchMultiplier = 5f;
    [SerializeField] float diagonalMatchMultiplier = 10f;
    [SerializeField] float clusterMultiplier = 2f; // Per symbol in cluster
    [SerializeField] float cornerMatchMultiplier = 15f;
    [SerializeField] float xPatternMultiplier = 20f;
    [SerializeField] float plusPatternMultiplier = 12f;
    [SerializeField] float framePatternMultiplier = 18f;
    
    [Header("Cluster Settings")]
    [SerializeField]
    int minClusterSize = 4;
    
    [Header("References")]
    [SerializeField]
    PlayerCredit playerCredit;
    
    [Header("UI References")]
    [SerializeField] private TMP_Text winAmountText;
    [SerializeField] private GameObject winDisplay;
    [SerializeField] private UnityEngine.UI.Image loseConditionImage;

    SlotState[,] slotGrid;
    List<PayoutResult> lastPayouts = new List<PayoutResult>();
    Color originalLoseImageColor;
    
    EventBinding<ColumnRollEvent> _columnRollBinding;
    EventBinding<RowRollEvent> _rowRollBinding;
    
    int pendingUpdates;
    
    void Start()
    {
        InitializeGrid();
        
        // Find PlayerCredit if not assigned
        if (playerCredit == null)
        {
            playerCredit = FindFirstObjectByType<PlayerCredit>();
        }
        
        // Store original lose condition image color
        if (loseConditionImage != null)
        {
            originalLoseImageColor = loseConditionImage.color;
        }
        
        // Subscribe to roll events
        _columnRollBinding = new EventBinding<ColumnRollEvent>(OnColumnRoll);
        EventBus<ColumnRollEvent>.Register(_columnRollBinding);
        
        _rowRollBinding = new EventBinding<RowRollEvent>(OnRowRoll);
        EventBus<RowRollEvent>.Register(_rowRollBinding);
    }
    
    void OnDisable()
    {
        // Unsubscribe from events
        EventBus<ColumnRollEvent>.Deregister(_columnRollBinding);
        EventBus<RowRollEvent>.Deregister(_rowRollBinding);
    }
    
    void OnColumnRoll(ColumnRollEvent evt)
    {
        // Count how many slots will update (entire column)
        pendingUpdates += gridSize;
        
        // Wait a frame for all updates to register, then check
        StartCoroutine(CheckForPayoutsAfterDelay());
    }
    
    void OnRowRoll(RowRollEvent evt)
    {
        // Count how many slots will update (entire row)
        pendingUpdates += gridSize;
        
        // Wait a frame for all updates to register, then check
        StartCoroutine(CheckForPayoutsAfterDelay());
    }
    
    System.Collections.IEnumerator CheckForPayoutsAfterDelay()
    {
        // Wait a short time for all slot updates to complete
        yield return new WaitForSeconds(0.1f);
        
        // Decrement pending updates
        pendingUpdates -= gridSize;
        
        // If all updates are complete, evaluate payouts
        if (pendingUpdates <= 0)
        {
            pendingUpdates = 0;
            
            // Raise RollCompleteEvent
            EventBus<RollCompleteEvent>.Raise(new RollCompleteEvent());
            
            EvaluatePayouts();
        }
    }
    
    void InitializeGrid()
    {
        slotGrid = new SlotState[gridSize, gridSize];
        
        // Get all child SlotState components
        SlotState[] slots = GetComponentsInChildren<SlotState>();
        
        foreach (SlotState slot in slots)
        {
            if (slot.row >= 0 && slot.row < gridSize && slot.column >= 0 && slot.column < gridSize)
            {
                slotGrid[slot.row, slot.column] = slot;
            }
        }
    }
    
    /// <summary>
    /// Evaluates all payout schemes and returns total winnings
    /// </summary>
    public int EvaluatePayouts()
    {
        lastPayouts.Clear();
        int totalPayout = 0;
        
        // Check all payout schemes
        totalPayout += CheckRowMatches();
        totalPayout += CheckColumnMatches();
        totalPayout += CheckDiagonalMatches();
        totalPayout += CheckClusters();
        totalPayout += CheckSpecialPatterns();
        
        // Award the payout
        if (totalPayout > 0 && playerCredit != null)
        {
            playerCredit.credits += totalPayout;
            
            // Raise WinEvent
            EventBus<WinEvent>.Raise(new WinEvent { WinAmount = totalPayout });
            Debug.Log($"Total Payout: {totalPayout} credits! Breakdown: {GetPayoutSummary()}");
            
            // Show win display
            ShowWinDisplay(totalPayout);
        }
        else
        {
            // Hide win display if no payout
            
            // Raise LoseEvent
            EventBus<LoseEvent>.Raise(new LoseEvent());
            HideWinDisplay();
            
            // Flash red for lose condition
            FlashLoseCondition();
        }
        
        return totalPayout;
    }
    
    #region Row Matches

    int CheckRowMatches()
    {
        int payout = 0;
        
        for (int row = 0; row < gridSize; row++)
        {
            // Check if all symbols in this row match
            int firstValue = slotGrid[row, 0].slotValue;
            bool allMatch = true;
            
            for (int col = 1; col < gridSize; col++)
            {
                if (!ValuesMatch(firstValue, slotGrid[row, col].slotValue))
                {
                    allMatch = false;
                    break;
                }
            }
            
            if (allMatch)
            {
                int rowPayout = Mathf.RoundToInt(playerCredit.betAmount * rowMatchMultiplier);
                payout += rowPayout;
                lastPayouts.Add(new PayoutResult($"Row {row} Match", rowPayout, firstValue));
            }
        }
        
        return payout;
    }
    #endregion
    
    #region Column Matches

    int CheckColumnMatches()
    {
        int payout = 0;
        
        for (int col = 0; col < gridSize; col++)
        {
            // Check if all symbols in this column match
            int firstValue = slotGrid[0, col].slotValue;
            bool allMatch = true;
            
            for (int row = 1; row < gridSize; row++)
            {
                if (!ValuesMatch(firstValue, slotGrid[row, col].slotValue))
                {
                    allMatch = false;
                    break;
                }
            }
            
            if (allMatch)
            {
                int colPayout = Mathf.RoundToInt(playerCredit.betAmount * columnMatchMultiplier);
                payout += colPayout;
                lastPayouts.Add(new PayoutResult($"Column {col} Match", colPayout, firstValue));
            }
        }
        
        return payout;
    }
    #endregion
    
    #region Diagonal Matches

    int CheckDiagonalMatches()
    {
        int payout = 0;
        
        // Check top-left to bottom-right diagonal
        int firstValue = slotGrid[0, 0].slotValue;
        bool allMatch = true;
        
        for (int i = 1; i < gridSize; i++)
        {
            if (!ValuesMatch(firstValue, slotGrid[i, i].slotValue))
            {
                allMatch = false;
                break;
            }
        }
        
        if (allMatch)
        {
            int diagPayout = Mathf.RoundToInt(playerCredit.betAmount * diagonalMatchMultiplier);
            payout += diagPayout;
            lastPayouts.Add(new PayoutResult("Diagonal \\ Match", diagPayout, firstValue));
        }
        
        // Check top-right to bottom-left diagonal
        firstValue = slotGrid[0, gridSize - 1].slotValue;
        allMatch = true;
        
        for (int i = 1; i < gridSize; i++)
        {
            if (!ValuesMatch(firstValue, slotGrid[i, gridSize - 1 - i].slotValue))
            {
                allMatch = false;
                break;
            }
        }
        
        if (allMatch)
        {
            int diagPayout = Mathf.RoundToInt(playerCredit.betAmount * diagonalMatchMultiplier);
            payout += diagPayout;
            lastPayouts.Add(new PayoutResult("Diagonal / Match", diagPayout, firstValue));
        }
        
        return payout;
    }
    #endregion
    
    #region Cluster Matches

    int CheckClusters()
    {
        int payout = 0;
        bool[,] visited = new bool[gridSize, gridSize];
        
        // Check each position for clusters
        for (int row = 0; row < gridSize; row++)
        {
            for (int col = 0; col < gridSize; col++)
            {
                if (!visited[row, col])
                {
                    int symbolValue = slotGrid[row, col].slotValue;
                    List<Vector2Int> cluster = new List<Vector2Int>();
                    
                    // Find all connected matching symbols using flood fill
                    FloodFill(row, col, symbolValue, visited, cluster);
                    
                    // Award payout if cluster is large enough
                    if (cluster.Count >= minClusterSize)
                    {
                        int clusterPayout = Mathf.RoundToInt(playerCredit.betAmount * clusterMultiplier * cluster.Count);
                        payout += clusterPayout;
                        lastPayouts.Add(new PayoutResult($"Cluster of {cluster.Count}", clusterPayout, symbolValue));
                    }
                }
            }
        }
        
        return payout;
    }

    void FloodFill(int row, int col, int targetValue, bool[,] visited, List<Vector2Int> cluster)
    {
        // Bounds check
        if (row < 0 || row >= gridSize || col < 0 || col >= gridSize)
            return;
        
        // Already visited
        if (visited[row, col])
            return;
        
        // Different symbol
        if (!ValuesMatch(targetValue, slotGrid[row, col].slotValue))
            return;
        
        // Mark as visited and add to cluster
        visited[row, col] = true;
        cluster.Add(new Vector2Int(col, row));
        
        // Check all 4 adjacent cells (up, down, left, right)
        FloodFill(row + 1, col, targetValue, visited, cluster);
        FloodFill(row - 1, col, targetValue, visited, cluster);
        FloodFill(row, col + 1, targetValue, visited, cluster);
        FloodFill(row, col - 1, targetValue, visited, cluster);
    }
    #endregion
    
    #region Special Patterns

    int CheckSpecialPatterns()
    {
        int payout = 0;
        
        payout += CheckCornerPattern();
        payout += CheckXPattern();
        payout += CheckPlusPattern();
        payout += CheckFramePattern();
        
        return payout;
    }
    
    /// <summary>
    /// Checks if all 4 corners match
    /// </summary>
    int CheckCornerPattern()
    {
        int topLeft = slotGrid[0, 0].slotValue;
        int topRight = slotGrid[0, gridSize - 1].slotValue;
        int bottomLeft = slotGrid[gridSize - 1, 0].slotValue;
        int bottomRight = slotGrid[gridSize - 1, gridSize - 1].slotValue;
        
        if (ValuesMatch(topLeft, topRight) && 
            ValuesMatch(topLeft, bottomLeft) && 
            ValuesMatch(topLeft, bottomRight))
        {
            int cornerPayout = Mathf.RoundToInt(playerCredit.betAmount * cornerMatchMultiplier);
            lastPayouts.Add(new PayoutResult("Four Corners", cornerPayout, topLeft));
            return cornerPayout;
        }
        
        return 0;
    }
    
    /// <summary>
    /// Checks if X pattern (both diagonals) match
    /// </summary>
    int CheckXPattern()
    {
        // Get all positions in X pattern
        List<int> xValues = new List<int>();
        
        // Main diagonal (top-left to bottom-right)
        for (int i = 0; i < gridSize; i++)
        {
            xValues.Add(slotGrid[i, i].slotValue);
        }
        
        // Anti-diagonal (top-right to bottom-left)
        for (int i = 0; i < gridSize; i++)
        {
            // Skip center if odd grid size (already counted)
            if (gridSize % 2 == 1 && i == gridSize / 2)
                continue;
            
            xValues.Add(slotGrid[i, gridSize - 1 - i].slotValue);
        }
        
        // Check if all values match
        int firstValue = xValues[0];
        bool allMatch = xValues.All(v => ValuesMatch(firstValue, v));
        
        if (allMatch)
        {
            int xPayout = Mathf.RoundToInt(playerCredit.betAmount * xPatternMultiplier);
            lastPayouts.Add(new PayoutResult("X Pattern", xPayout, firstValue));
            return xPayout;
        }
        
        return 0;
    }
    
    /// <summary>
    /// Checks if Plus (+) pattern matches (middle row and column)
    /// </summary>
    int CheckPlusPattern()
    {
        if (gridSize % 2 == 0) return 0; // Only works with odd grid sizes
        
        int middle = gridSize / 2;
        List<int> plusValues = new List<int>();
        
        // Middle row
        for (int col = 0; col < gridSize; col++)
        {
            plusValues.Add(slotGrid[middle, col].slotValue);
        }
        
        // Middle column (skip center as already counted)
        for (int row = 0; row < gridSize; row++)
        {
            if (row == middle) continue;
            plusValues.Add(slotGrid[row, middle].slotValue);
        }
        
        // Check if all values match
        int firstValue = plusValues[0];
        bool allMatch = plusValues.All(v => ValuesMatch(firstValue, v));
        
        if (allMatch)
        {
            int plusPayout = Mathf.RoundToInt(playerCredit.betAmount * plusPatternMultiplier);
            lastPayouts.Add(new PayoutResult("Plus Pattern", plusPayout, firstValue));
            return plusPayout;
        }
        
        return 0;
    }
    
    /// <summary>
    /// Checks if outer frame (all edge cells) match
    /// </summary>
    int CheckFramePattern()
    {
        List<int> frameValues = new List<int>();
        
        // Top and bottom rows
        for (int col = 0; col < gridSize; col++)
        {
            frameValues.Add(slotGrid[0, col].slotValue);
            frameValues.Add(slotGrid[gridSize - 1, col].slotValue);
        }
        
        // Left and right columns (excluding corners already counted)
        for (int row = 1; row < gridSize - 1; row++)
        {
            frameValues.Add(slotGrid[row, 0].slotValue);
            frameValues.Add(slotGrid[row, gridSize - 1].slotValue);
        }
        
        // Check if all values match
        int firstValue = frameValues[0];
        bool allMatch = frameValues.All(v => ValuesMatch(firstValue, v));
        
        if (allMatch)
        {
            int framePayout = Mathf.RoundToInt(playerCredit.betAmount * framePatternMultiplier);
            lastPayouts.Add(new PayoutResult("Frame Pattern", framePayout, firstValue));
            return framePayout;
        }
        
        return 0;
    }
    #endregion
    
    #region Helper Methods
    /// <summary>
    /// Checks if two slot values match, considering wildcards
    /// </summary>
    bool ValuesMatch(int value1, int value2)
    {
        if (enableWildcards && wildcardValue >= 0)
        {
            // Wildcard matches anything
            if (value1 == wildcardValue || value2 == wildcardValue)
                return true;
        }
        
        return value1 == value2;
    }

    string GetPayoutSummary()
    {
        if (lastPayouts.Count == 0)
            return "No wins";
        
        return string.Join(", ", lastPayouts.Select(p => $"{p.description} (+{p.amount})"));
    }
    
    /// <summary>
    /// Shows the win display and updates the win amount text
    /// </summary>
    void ShowWinDisplay(int winAmount)
    {
        if (winDisplay != null)
        {
            winDisplay.SetActive(true);
        }
        
        if (winAmountText != null)
        {
            winAmountText.text = $"<color=#B3B5C7><size=65%>Amount Won:</size></color> {winAmount}";
        }
    }
    
    /// <summary>
    /// Hides the win display
    /// </summary>
    void HideWinDisplay()
    {
        if (winDisplay != null)
        {
            winDisplay.SetActive(false);
        }
    }
    
    /// <summary>
    /// Flashes the lose condition image red for 2 seconds
    /// </summary>
    void FlashLoseCondition()
    {
        if (loseConditionImage != null)
        {
            StartCoroutine(FlashLoseConditionCoroutine());
        }
    }
    
    System.Collections.IEnumerator FlashLoseConditionCoroutine()
    {
        // Change to red
        loseConditionImage.color = Color.red;
        
        // Wait for 2 seconds
        yield return new WaitForSeconds(2f);
        
        // Change back to original color
        loseConditionImage.color = originalLoseImageColor;
    }
    
    /// <summary>
    /// Debug method to print the current grid state
    /// </summary>
    [ContextMenu("Print Grid State")]
    public void PrintGridState()
    {
        string gridString = "Current Grid State:\n";
        
        for (int row = 0; row < gridSize; row++)
        {
            for (int col = 0; col < gridSize; col++)
            {
                if (slotGrid[row, col] != null)
                {
                    gridString += slotGrid[row, col].slotValue + " ";
                }
                else
                {
                    gridString += "X ";
                }
            }
            gridString += "\n";
        }
        
        Debug.Log(gridString);
    }
    
    /// <summary>
    /// Debug method to test payout evaluation
    /// </summary>
    [ContextMenu("Test Payout Evaluation")]
    public void TestPayoutEvaluation()
    {
        if (slotGrid == null || slotGrid[0, 0] == null)
        {
            InitializeGrid();
        }
        
        PrintGridState();
        int payout = EvaluatePayouts();
        Debug.Log($"Total Payout: {payout}");
    }
    #endregion
}

/// <summary>
/// Represents a single payout result
/// </summary>
[System.Serializable]
public class PayoutResult
{
    public string description;
    public int amount;
    public int symbolValue;
    
    public PayoutResult(string description, int amount, int symbolValue)
    {
        this.description = description;
        this.amount = amount;
        this.symbolValue = symbolValue;
    }
}
